name: process-json-files

on:
  push:
    paths:
      - 'data/eval/**/*.json'

permissions:
  contents: read
  pull-requests: write

jobs:
  detectar_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: Move to source folder
        run: cd src

      - name: Install dependencies
        run: pip install pandas
        
      - name: Run script
        run: python src/process_qa_json.py

      - name: Commit files
        id: commit
        run: |
          git config --local user.email "alberteinstein.al@gmail.com"
          git config --local user.name "AlbertoUAH"
          git add --all
          if [-z "$(git status --porcelain)"]; then
             echo "::set-output name=push::false"
          else
             git commit -m "Process .json files" -a
             echo "::set-output name=push::true"
             git push
          fi
        shell: bash
