name: process-json-files

on:
  push:
    paths:
      - 'data/eval/**/*.json'

jobs:
  detectar_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install pandas
        
      - name: Run script
        run: python src/process_qa_json.py
